#!/usr/bin/env python3
"""Install genuine pinned Prek hooks with documented canonical execution.

Install the owning pinned upstream checker implementations faithfully.
The helper transforms only the real generated Prek pre-commit script and leaves
its actual checker, executable and arguments intact, then reconciles managed
Repro hooks. All integration controls use real tools/filesystem; no mocks.
"""
from __future__ import annotations
import argparse
import hashlib
import os
from pathlib import Path
import shutil
import stat
import subprocess
import sys
import tempfile

CONTRACT = "reprobuild.managed-hook.v1.pre-commit.434c2eeac4079591"
EXPORT = b"export PREK_NO_FAST_PATH=1\n"
GENERATED = b"# File generated by prek: https://github.com/j178/prek\n"

def run(argv: list[str], cwd: Path) -> str:
    return subprocess.check_output(argv, cwd=cwd, text=True, stderr=subprocess.STDOUT).strip()

def selected_tool(name: str) -> str:
    found = shutil.which(name)
    if not found:
        raise RuntimeError(f"missing declared native tool: {name}")
    return str(Path(found).absolute())

def canonical_generated_body(body: bytes, prek: str) -> bytes:
    if not body.startswith(b"#!/usr/bin/env bash\n") or GENERATED not in body:
        raise RuntimeError("unexpected actual generated Prek hook template")
    if b"reprobuild hook dispatcher" in body:
        raise RuntimeError("refusing to transform managed dispatcher")
    if body.count(b'exec "$PREK" "${ARGS[@]}"') != 1:
        raise RuntimeError("unexpected native hook execution template")
    if body.count(b"ARGS=(hook-impl --hook-type=pre-commit --script-version=3)") != 1:
        raise RuntimeError("unexpected native hook type/version")
    binding = ('PREK="' + prek + '"').encode()
    if body.count(binding) != 1:
        raise RuntimeError("generated hook native executable differs from selected pinned Prek")
    if EXPORT in body:
        raise RuntimeError("unexpected premodified generated native hook")
    first, rest = body.split(b"\n", 1)
    result = first + b"\n" + EXPORT + rest
    if result.replace(EXPORT, b"", 1) != body:
        raise RuntimeError("native template byte transformation failed")
    return result

def atomic_write(path: Path, data: bytes, mode: int) -> None:
    descriptor, filename = tempfile.mkstemp(prefix=".canonical-prek-", dir=path.parent)
    temporary = Path(filename)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(mode)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repro", required=True, help="explicit measured matching managed-hook engine")
    args = parser.parse_args()
    root = Path.cwd().resolve()
    git = selected_tool("git")
    prek = selected_tool("prek")
    repro = Path(args.repro).absolute()
    if not repro.is_file() or not os.access(repro, os.X_OK):
        raise RuntimeError("missing selected matching Repro executable")
    if Path(run([git, "rev-parse", "--show-toplevel"], root)).resolve() != root:
        raise RuntimeError("run from actual owning repository root")
    if not (root / ".pre-commit-config.yaml").is_file():
        raise RuntimeError("missing owning portable standard config")
    if run([prek, "--version"], root) != "prek 0.2.17":
        raise RuntimeError("unqualified native Prek version")
    if run([str(repro), "hooks", "protocol", "--require=2", "--hook-contract=" + CONTRACT], root) != "2":
        raise RuntimeError("matching managed hook protocol failed")
    git_dir = Path(run([git, "rev-parse", "--absolute-git-dir"], root)).resolve()
    common_raw = Path(run([git, "rev-parse", "--git-common-dir"], root))
    common = (root / common_raw).resolve() if not common_raw.is_absolute() else common_raw.resolve()
    if git_dir != common or not common.is_relative_to(root):
        raise RuntimeError("shared/external Git hook ownership requires separate qualification")
    hooks = common / "hooks"
    if hooks.is_symlink() or (hooks.exists() and not hooks.is_dir()):
        raise RuntimeError("own hooks directory is symlink or non-directory")
    configured = subprocess.run([git, "config", "--get", "core.hooksPath"], cwd=root, text=True, capture_output=True)
    if configured.returncode not in (0, 1):
        raise RuntimeError("cannot inspect own hook path")
    if configured.returncode == 0:
        raw = Path(configured.stdout.strip())
        resolved = (root / raw).resolve() if not raw.is_absolute() else raw.resolve()
        if resolved != hooks:
            raise RuntimeError("nonowning or unqualified hooks directory")
    actual_hooks = Path(run([git, "rev-parse", "--path-format=absolute", "--git-path", "hooks"], root))
    if actual_hooks.is_symlink() or actual_hooks.resolve() != hooks.resolve():
        raise RuntimeError("effective Git hooks path is not the owning directory")
    if actual_hooks.exists() and not actual_hooks.is_dir():
        raise RuntimeError("effective hooks path is non-directory")
    hooks.mkdir(exist_ok=True)
    original_pre_push = {p.name: p.read_bytes() for p in hooks.glob("pre-push*") if p.is_file() and not p.is_symlink()}
    env = os.environ.copy()
    env["PREK_NO_FAST_PATH"] = "1"
    env["REPROBUILD_REPRO"] = str(repro)
    # The owning config requires language_version system; Prek refuses
    # managed Python downloads. The locked SDK supplies native Python on PATH.
    existing = hooks / "pre-commit"
    if existing.is_symlink():
        raise RuntimeError("unowned existing pre-commit symlink")
    if existing.exists():
        if existing.is_symlink() or not existing.is_file():
            raise RuntimeError("unowned existing pre-commit hook shape")
        previous = existing.read_bytes()
        if not previous.startswith(b"#!/usr/bin/env sh\n# reprobuild hook dispatcher protocol=2\n"):
            canonical_generated_body(previous.replace(EXPORT, b"", 1), prek)
    preserved = hooks / "pre-commit.repro-local"
    preserved_before = None
    if preserved.is_symlink():
        raise RuntimeError("unowned preserved local hook symlink")
    if preserved.exists():
        if preserved.is_symlink() or not preserved.is_file():
            raise RuntimeError("unowned preserved local hook shape")
        preserved_before = preserved.read_bytes()
        canonical_generated_body(preserved_before.replace(EXPORT, b"", 1), prek)
    try:
        subprocess.run([prek, "install", "--install-hooks"], cwd=root, env=env, check=True)
        generated = hooks / "pre-commit"
        if generated.is_symlink() or not generated.is_file():
            raise RuntimeError("actual generated local pre-commit is not owned regular file")
        body = generated.read_bytes()
        mode = stat.S_IMODE(generated.stat().st_mode)
        if not mode & stat.S_IXUSR:
            raise RuntimeError("generated native hook is not executable")
        canonical = canonical_generated_body(body, prek)
        atomic_write(generated, canonical, mode)
        if preserved.is_symlink() or (preserved.exists() and not preserved.is_file()):
            raise RuntimeError("preserved local hook changed shape during installation")
        if preserved.exists() != (preserved_before is not None):
            raise RuntimeError("preserved local hook created or disappeared during installation")
        if preserved_before is not None:
            # Reconcile the already validated owning template, retaining its
            # exact former bytes before replacing only this local checker.
            if preserved.read_bytes() != preserved_before:
                raise RuntimeError("preserved local hook changed during installation")
            backup = hooks / ("pre-commit.repro-local.backup-" + hashlib.sha256(preserved_before).hexdigest())
            if backup.is_symlink() or (backup.exists() and (not backup.is_file() or backup.read_bytes() != preserved_before)):
                raise RuntimeError("unowned preserved-template backup")
            if not backup.exists():
                atomic_write(backup, preserved_before, stat.S_IMODE(preserved.stat().st_mode))
            atomic_write(preserved, canonical, mode)
    finally:
        # Even installation/template failure must leave the managed dispatcher
        # reconciled; no commit is attempted on a failed canonical installation.
        subprocess.run([str(repro), "hooks", "ensure", "--vcs", "."], cwd=root, env=env, check=True)
        for name, contents in original_pre_push.items():
            target = hooks / name
            if not target.is_file() or target.is_symlink() or target.read_bytes() != contents:
                raise RuntimeError(f"pre-push contract changed: {name}")
    local = hooks / "pre-commit.repro-local"
    if local.is_symlink() or local.read_bytes() != canonical:
        raise RuntimeError("reconciled local hook did not preserve canonical native script")
    for name, contents in original_pre_push.items():
        target = hooks / name
        if not target.is_file() or target.is_symlink() or target.read_bytes() != contents:
            raise RuntimeError(f"pre-push contract changed: {name}")
    print("Canonical pinned hook installed; local bytes SHA256=" + hashlib.sha256(canonical).hexdigest())

if __name__ == "__main__":
    main()
